Repository RedHatCRE/syncron, pull requests merged in 2022-11, with the labels that each got.

#18 Implement file downloads
  cmd/adhoc/cmd/download.go
  pkg/bucketaws/setup.go
  utils/files.go
Labels: feature

#19 Updated README with more relevant information
  README.md
Labels: documentation

#23 Added download time on each file.
  pkg/bucketaws/setup.go
Labels: enhancement

#26 Fix config path
  .gitignore
  README.md
  pkg/bucketaws/setup.go
Labels: bug

#27 Fix absolute path
  pkg/bucketaws/setup.go
  utils/files.go
Labels: bug

#28 Component filter
  .gitignore
  cmd/syncron/download.go
  go.mod
  go.sum
  pkg/bucketaws/setup.go
  pkg/cli/args.go
  utils/files/files.go
  utils/filter/filter.go
Labels: feature

#29 Add golangcli-lint
  .github/workflows/on-change.yaml
  cmd/syncron/download.go
  pkg/log/config_test.go
  utils/files/files.go
Labels: test

#31 Fix for no items found
  cmd/syncron/download.go
  utils/filter/filter.go
Labels: bug

#35 Adding configuration struct to avoid calling viper everywhere
  README.md
  cmd/syncron/download.go
  configuration/configuration.go
  pkg/bucketaws/setup.go
  utils/files/files.go
Labels: enhancement
